---
version: 2
updates:
  - package-ecosystem: gradle
    directory: "/plugins"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
