---
- name: Configure JCasC configuration file
  ansible.builtin.template:
    src: "{{ jenkins_jcasc_config_file }}"
    dest: "{{ jenkins_config_dir }}/jenkins.yaml"
    mode: "0644"

- name: Create intermediate dirs for custom files
  ansible.builtin.file:
    path: "{{ jenkins_home }}/{{ custom_file.dest | dirname }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0755"
    state: directory
  with_items: "{{ jenkins_custom_files }}"
  loop_control:
    loop_var: custom_file

- name: Configure custom files
  ansible.builtin.template:
    src: "{{ custom_file.src }}"
    dest: "{{ jenkins_home }}/{{ custom_file.dest }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"
  with_items: "{{ jenkins_custom_files }}"
  loop_control:
    loop_var: custom_file

- name: Copy secrets
  ansible.builtin.copy:
    src: "{{ secret_file }}"
    dest: "{{ jenkins_secrets_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0600"
  with_items: "{{ jenkins_secret_files }}"
  loop_control:
    loop_var: secret_file

- name: Copy userContent
  ansible.builtin.copy:
    src: "{{ jenkins_user_content }}/"
    dest: "{{ jenkins_user_content_dir }}/"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"
  when: jenkins_user_content != ""
