---
- name: Generate Jenkins systemd service file
  template:
    src: "jenkins.service.j2"
    dest: "/etc/systemd/system/jenkins.service"
    mode: "0644"

- name: Ensure systemd service runs at boot
  systemd:
    name: "jenkins"
    enabled: true
    daemon_reload: true
    state: stopped
