---
# We need to make a subdirectory for JCasC configuration files, since the JCasC plugin
# examines all YAML files in this directory and we'll also put the plugins.yaml file here,
# which isn't meant for JCasC.
- name: Ensure JCasC configuration subdirectory exists
  become: true
  ansible.builtin.file:
    path: "{{ jenkins_config_dir }}/jcasc/"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0755"
    state: directory

- name: Configure JCasC configuration files
  become: true
  ansible.builtin.template:
    src: "{{ config_file }}"
    dest: "{{ jenkins_config_dir }}/jcasc/\
      {{ config_file | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"
  loop: "{{ jenkins_jcasc_config_files }}"
  loop_control:
    loop_var: config_file

- name: Create intermediate dirs for custom files
  become: true
  ansible.builtin.file:
    path: "{{ jenkins_home }}/{{ custom_file.dest | dirname }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0755"
    state: directory
  loop: "{{ jenkins_custom_files }}"
  loop_control:
    loop_var: custom_file

- name: Configure custom files
  become: true
  ansible.builtin.template:
    src: "{{ custom_file.src }}"
    dest: "{{ jenkins_home }}/{{ custom_file.dest }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"
  loop: "{{ jenkins_custom_files }}"
  loop_control:
    loop_var: custom_file

- name: Copy secrets
  become: true
  ansible.builtin.copy:
    src: "{{ secret_file }}"
    dest: "{{ jenkins_secrets_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0600"
  loop: "{{ jenkins_secret_files }}"
  loop_control:
    loop_var: secret_file

- name: Copy userContent
  become: true
  ansible.builtin.copy:
    src: "{{ jenkins_user_content }}/"
    dest: "{{ jenkins_user_content_dir }}/"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"
  when: jenkins_user_content != ""
