---
- name: Configure JCasC configuration file
  template:
    src: "{{ jenkins_jcasc_config_file }}"
    dest: "{{ jenkins_config_dir }}/jenkins.yaml"

- name: Create intermediate dirs for custom files
  file:
    path: "{{ jenkins_home }}/{{ custom_file.dest | dirname }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0755"
    state: directory
  with_items: "{{ jenkins_custom_files }}"
  loop_control:
    loop_var: custom_file

- name: Configure custom files
  template:
    src: "{{ custom_file.src }}"
    dest: "{{ jenkins_home }}/{{ custom_file.dest }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"
  with_items: "{{ jenkins_custom_files }}"
  loop_control:
    loop_var: custom_file

- name: Copy userContent
  copy:
    src: "{{ jenkins_user_content }}/"
    dest: "{{ jenkins_userContent_dir }}/"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
  when: jenkins_user_content != ""
