---
- name: Job directories are present
  ansible.builtin.file:
    path: "{{ jenkins_home }}/jobs/{{ job_name }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0777"
    state: directory
  with_items: "{{ jenkins_jobs }}"
  loop_control:
    loop_var: job_name

- name: Jobs are present
  ansible.builtin.copy:
    src: "{{ jenkins_jobs_dir }}/{{ job_name }}/config.xml"
    dest: "{{ jenkins_home }}/jobs/{{ job_name }}/config.xml"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0777"
  with_items: "{{ jenkins_jobs }}"
  loop_control:
    loop_var: job_name
