---
- name: Ensure Java is installed
  become: true
  ansible.builtin.apt:
    name: "{{ jenkins_java_package }}"
    state: present
    update_cache: true

- name: Ensure daemon is installed
  become: true
  ansible.builtin.apt:
    name: "daemon"
    state: present
  when: ansible_service_mgr == "sysvinit"
