---
- name: Download Jenkins WAR file
  become: true
  ansible.builtin.get_url:
    url: "https://mirrors.jenkins.io/war-stable/{{ jenkins_version }}/jenkins.war"
    checksum: "sha256:\
      https://mirrors.jenkins.io/war-stable/{{ jenkins_version }}/jenkins.war.sha256"
    dest: "{{ jenkins_war }}"
    # Sometimes the main Jenkins repository has network stability issues
    timeout: "{{ jenkins_download_timeout }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"
  retries: "{{ jenkins_download_retries }}"
  delay: "{{ jenkins_download_delay }}"
  register: download_jenkins_war_result
  until: download_jenkins_war_result is succeeded
