---
- name: Download Jenkins WAR file
  ansible.builtin.get_url:
    url: "https://mirrors.jenkins.io/war-stable/{{ jenkins_version }}/jenkins.war"
    checksum: "sha256:\
      https://mirrors.jenkins.io/war-stable/{{ jenkins_version }}/jenkins.war.sha256"
    dest: "{{ jenkins_war }}"
    # Sometimes the main Jenkins repository has network stability issues
    timeout: 30
    mode: "0644"
  retries: 3
