---
- name: Ensure Java is installed
  ansible.builtin.apt:
    name: "openjdk-11-jre-headless"
    state: present
    update_cache: true

- name: Ensure daemon is installed
  ansible.builtin.apt:
    name: "daemon"
    state: present
  when: ansible_service_mgr == "sysvinit"
