---
- name: Copy plugins file
  ansible.builtin.template:
    src: "{{ jenkins_plugins_file }}"
    dest: "{{ jenkins_config_dir }}/plugins.yaml"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"

# Plugins are installed to a temporary directory because otherwise the permissions on the
# real plugin directory get screwed up, and adding another task to fix that would be
# idempotent. Also, if the plugins are copied to the real directory after downloading,
# we'll get useful information in the Ansible logs about which ones have changed.
- name: Install plugins to temporary directory
  become: true
  become_user: "{{ jenkins_user }}"
  ansible.builtin.command: >
    java -jar
      {{ jenkins_pimt_path }}
      --plugin-download-directory /tmp/plugins
      --plugin-file {{ jenkins_config_dir }}/plugins.yaml
      --war {{ jenkins_war }}
      --latest false
      --verbose
  environment:
    CACHE_DIR: "{{ jenkins_caches_dir }}"
  # We don't have a good way to know when this command changed anything on the system, so
  # we take the coward's way out and just define changed_when to false. The next task will
  # report an accurate changed status, however.
  changed_when: false
  retries: 3
  delay: 5
  register: plugin_installation_result
  until: plugin_installation_result is success

- name: Find all plugins downloaded by Plugin Installation Manager Tool
  ansible.builtin.find:
    paths:
      - "/tmp/plugins"
    patterns:
      - "*.hpi"
      - "*.jpi"
  register: downloaded_plugins

# We could copy the entire directory where we downloaded the plugins by setting the src to
# be "/tmp/plugins/", but then we miss out on seeing which plugins were actually changed.
# The cost of this is a bit of extra runtime, but it's worth it to see which plugins have
# been updated.
- name: Copy plugins to Jenkins plugin directory
  ansible.builtin.copy:
    src: "{{ plugin_file }}"
    dest: "{{ jenkins_plugins_dir }}"
    remote_src: true
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"
  with_items: "{{ downloaded_plugins.files | map(attribute='path') | list }}"
  loop_control:
    loop_var: plugin_file

# This should be done in order to ensure that older versions of JCasC and its dependencies
# aren't installed to the controller.
- name: Clean plugin dependencies directory
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ role_path }}/plugins/target"
    state: absent
  # To satisfy Molecule, which would complain about this task being non-idempotent.
  changed_when: false

- name: Fetch plugin dependencies with Gradle on Ansible control node
  become: false
  delegate_to: localhost
  ansible.builtin.command: "./gradlew getDeps"
  args:
    chdir: "{{ role_path }}/plugins"
  changed_when: false

- name: Find all plugins downloaded by Gradle on Ansible control node
  become: false
  delegate_to: localhost
  ansible.builtin.find:
    paths:
      - "{{ role_path }}/plugins/target"
    patterns:
      - "*.hpi"
      - "*.jpi"
  register: role_custom_plugins

- name: Collect JCasC plugins in jenkins_jcasc_plugins list
  ansible.builtin.set_fact:
    jenkins_jcasc_plugins: >
      {{ role_custom_plugins.files | map(attribute='path') | list }}

# We install custom plugins AFTER installing everything else with the plugin installation
# manager tool. This allows us to ensure that these plugins are not overridden by a
# different and possibly conflicting version.
- name: Install custom Jenkins plugins
  ansible.builtin.copy:
    src: "{{ plugin_file }}"
    dest: "{{ jenkins_plugins_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"
  with_items: "{{ jenkins_jcasc_plugins + jenkins_custom_plugins }}"
  loop_control:
    loop_var: plugin_file
