---
- name: Ensure that required role variables are defined
  ansible.builtin.fail:
    msg: "Undefined required role variable (s)"
  when: required_variable == ""
  loop_control:
    loop_var: required_variable
  with_items:
    - "{{ jenkins_group }}"
    - "{{ jenkins_home }}"
    - "{{ jenkins_jcasc_config_file }}"
    - "{{ jenkins_jcasc_version }}"
    - "{{ jenkins_pimt_version }}"
    - "{{ jenkins_plugins_file }}"
    - "{{ jenkins_port }}"
    - "{{ jenkins_prefix }}"
    - "{{ jenkins_root }}"
    - "{{ jenkins_user }}"
    - "{{ jenkins_version }}"

- name: Ensure that jobs directory is defined if necessary
  ansible.builtin.fail:
    msg: "jenkins_jobs is not empty, but jenkins_jobs_dir is undefined"
  when: (jenkins_jobs | length > 0) and jenkins_jobs_dir == ""

- name: Ensure prefix starts with slash
  ansible.builtin.fail:
    msg: "jenkins_prefix needs to start with slash (/)"
  when: not jenkins_prefix.startswith("/")

- name: Read plugins.yaml file
  ansible.builtin.set_fact:
    jenkins_plugins_file_data: >-
      {{ lookup('ansible.builtin.file', jenkins_plugins_file) | from_yaml }}

- name: Check if configuration-as-code plugin is defined in plugins.yaml data
  ansible.builtin.set_fact:
    jenkins_jcasc_plugin_found: true
  when: item.artifactId == "configuration-as-code"
  loop: "{{ jenkins_plugins_file_data.plugins }}"

- name: Fail if configuration-as-code plugin was not found in plugins.yaml
  ansible.builtin.fail:
    msg: "The configuration-as-code (JCasC) plugin was not found in plugins.yaml"
  when: jenkins_jcasc_plugin_found is not defined
