---
- name: Converge
  hosts: all
  vars:
    ansible_user: "molecule"
    jenkins_custom_files:
      - src: "{{ playbook_dir }}/files/sidebar-link.xml"
        dest: "sidebar-link.xml"
    jenkins_extra_args: "--sessionTimeout=1"
    jenkins_group: "jgroup"
    jenkins_java_args: "-server"
    jenkins_jcasc_config_file: "{{ playbook_dir }}/configs/jenkins.yaml"
    jenkins_jobs:
      - "test_job"
    jenkins_jobs_dir: "{{ playbook_dir }}/jobs"
    jenkins_pimt_logfile: "/tmp/pimt.log"
    jenkins_plugins_file: "{{ playbook_dir }}/configs/plugins.yaml"
    jenkins_port: "8100"
    jenkins_prefix: "/j"
    jenkins_root: "/jenkins"
    jenkins_secret_files:
      - "{{ playbook_dir }}/files/secret.txt"
    jenkins_user: "juser"
    jenkins_users:
      alice:
        password: "notsecure"
      bob:
        api_token: "112a1dfb4ac8209130c4b630efe824f589"
      carol:
        password: "changeme"
        api_token: "11c8f304eb91ab249386a2d929f28804e5"
    jenkins_user_content: "{{ playbook_dir }}/files/userContent"
    jenkins_version: "2.401.3"
  roles:
    - ableton.jenkins_jcasc
