{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN apt-get update && \
    apt-get install -y acl ca-certificates gnupg python3 python3-apt sudo && \
    apt-get clean

ENV ANSIBLE_USER=molecule ANSIBLE_GROUP=molecule
ENV SUDO_GROUP=sudo
RUN set -xe \
  && groupadd -r ${ANSIBLE_GROUP} \
  && useradd -m -g ${ANSIBLE_GROUP} ${ANSIBLE_USER} \
  && usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} \
  && usermod -aG ${ANSIBLE_GROUP} ${ANSIBLE_USER} \
  && sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers
